language: python

python:
  - 2.6
  - 2.7
  - 3.1
  - 3.2

install:
  - pip install --use-mirrors nose numpy
  - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then pip install --use-mirrors PIL; fi
  - pip install .

script:
  - mkdir ../foo
  - cd ../foo
  - python ../matplotlib/tests.py
